"""Initial migration.

Revision ID: 1dcce6390cd6
Revises: 
Create Date: 2024-03-26 00:49:49.376244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcce6390cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('manualdata',
    sa.Column('id_m', sa.Integer(), nullable=False),
    sa.Column('hum', sa.Float(), nullable=False),
    sa.Column('soil_nitro1', sa.Float(), nullable=False),
    sa.Column('soil_phos1', sa.Float(), nullable=False),
    sa.Column('soil_pot1', sa.Float(), nullable=False),
    sa.Column('soil_temp1', sa.Float(), nullable=False),
    sa.Column('soil_ph1', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.String(length=250), nullable=False),
    sa.Column('updated_at', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id_m')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manualdata')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))

    op.drop_table('admin')
    # ### end Alembic commands ###
