"""empty message

Revision ID: 61b4dd3fcdb1
Revises: 10b41429358a
Create Date: 2024-05-15 21:42:08.343523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4dd3fcdb1'
down_revision = '10b41429358a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=250), nullable=False),
    sa.Column('area_longitude', sa.Float(), nullable=True),
    sa.Column('area_latitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=250), nullable=False),
    sa.Column('updated_at', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['manualdata.id_m'], ),
    sa.PrimaryKeyConstraint('id_area')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
