"""feat:area column on manualdata tabel

Revision ID: 64352b38efc4
Revises: 61b4dd3fcdb1
Create Date: 2024-05-15 22:15:34.600489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64352b38efc4'
down_revision = '61b4dd3fcdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualdata', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
