"""empty message

Revision ID: 972e460c90e3
Revises: 8fa7201df485
Create Date: 2024-05-24 08:52:38.126136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972e460c90e3'
down_revision = '8fa7201df485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
