"""feat:add foreign key on area

Revision ID: a22029735c49
Revises: 972e460c90e3
Create Date: 2024-06-20 15:53:28.616544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22029735c49'
down_revision = '972e460c90e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_d', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_area_dataset', 'dataset', ['id_d'], ['id_d'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_constraint('fk_area_dataset', type_='foreignkey')
        batch_op.drop_column('id_d')

    # ### end Alembic commands ###
