"""Third Commit

Revision ID: b42d1c41a3ab
Revises: 62d763099580
Create Date: 2024-03-15 14:00:40.981647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42d1c41a3ab'
down_revision = '62d763099580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manualdata',
    sa.Column('id_m', sa.Integer(), nullable=False),
    sa.Column('hum', sa.Float(), nullable=False),
    sa.Column('soil_nitro1', sa.Float(), nullable=False),
    sa.Column('soil_phos1', sa.Float(), nullable=False),
    sa.Column('soil_pot1', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.String(length=250), nullable=False),
    sa.Column('updated_at', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id_m')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manualdata')
    # ### end Alembic commands ###
